### ISSUE TITLE
Error: no such module 'Reductio'

### ISSUE THREAD

**Issue by kimsanov** [fdzsergio/Reductio#4]
Hi!
Downloaded Reductio. When I open Reductio.xcworkspace and build – everything is good. But playground gives error:
`Playground execution failed: error: Reductio.playground:6:8: error: no such module 'Reductio'`
`import Reductio`

My Xcode version 8.3.2

**Comment by sriteja25** [comment]
Any update ?

**Comment by fdzsergio** [comment]
Checkout new version with Xcode 10
